services:
  docs:
    container_name: "docs"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - KROKI_BASE_URL=http://kroki:8000
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "pnpm build:api-doc && pnpm turbo dev --filter=docs"
    volumes:
      - ./arch/diagrams:/app/apps/docs/arch/diagrams
      - ./arch/documentations:/app/apps/docs/arch/content/docs
      - ./arch/api:/app/apps/docs/api-doc-gen
    depends_on:
      - kroki

  kroki:
    container_name: "kroki"
    image: yuzutech/kroki:latest
    ports:
      - "8000:8000"
