name: Docker Build and Deploy

on:
  push:
    branches: ["example"] # Triggers on push to the example branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: make static-prod-build

      - name: Extract Static Files from Docker
        run: |
          # Create a temporary container
          docker create --name temp-container architecture-static
          # Copy the 'out' folder from container to Runner
          docker cp temp-container:/app/out ./static-out
          docker rm temp-container

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./static-out # Upload files extracted from Docker

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
